"""ChangeRequestBackend — DeepAgents filesystem backend that captures writes.

Core principle: the LLM never writes to ``.md`` files directly. This backend subclasses
the ``FilesystemBackend`` from DeepAgents and overrides write operations
(``write``/``edit`` and async variants) to store content in an in-memory *staging*
area instead of writing to disk. Reads come from the real disk, overlaid with the
staging area (the agent sees what it has "written" in this run).

Write guardrails (defence in depth — enforced in code, not only in the prompt):

- Writes are confined to ``wiki/`` (allow-list). Everything else — ``raw/``,
  ``.llmwiki/``, the brain root, etc. — is rejected.
- The generated files ``wiki/index.md`` and ``wiki/log.md`` are immutable to the
  agent (they are produced by the indexing service / skill).
- Only Markdown (``.md``) files can be written.
- In ``read_only`` mode every write is rejected and recorded in
  ``write_attempts`` (used by read-only operations such as ``ask`` to audit
  unexpected write attempts instead of silently dropping them).

Listing/searching (``ls``/``grep``/``glob``) are overlaid with the staging area so
the agent sees the pages it has written in this same run — preventing it from
creating a duplicate page just because the first page is not on disk yet.

At the end of the run, ``collect_changes()`` compares staging with the disk and
returns a list of ``FileChange`` (with diffs) that becomes the change request.
"""

from __future__ import annotations

import logging
from collections.abc import Callable
from fnmatch import fnmatch
from pathlib import Path, PurePosixPath

from deepagents.backends import FilesystemBackend
from deepagents.backends.protocol import (
    EditResult,
    FileData,
    FileInfo,
    GlobResult,
    GrepMatch,
    GrepResult,
    LsResult,
    ReadResult,
    WriteResult,
)

from ..core.diff import make_diff
from ..core.models import FileChange
from .telemetry import ExecutionMeta

logger = logging.getLogger("llmwiki.llm_agents.backend")

_RAW_PREFIX = "raw/"
_WIKI_PREFIX = "wiki/"
# Files generated by the indexing service / wiki-ingest skill — never the agent.
_GENERATED = frozenset({"wiki/index.md", "wiki/log.md"})


def validate_change_path(file_path: str) -> str | None:
    """Allow-list check for a change-request path (no filesystem access).

    Shared by the backend (staging guard) and ``apply()`` (defence in depth when
    writing to disk). Returns an error message if the path must NOT be
    written/applied, else ``None``.

    Policy: only ``wiki/**/*.md`` (minus generated files) is allowed; no path
    traversal, no ``raw/``.
    """
    norm = file_path.lstrip("/")
    if ".." in PurePosixPath(norm).parts:
        return "path traversal is not allowed."
    if norm.startswith(_RAW_PREFIX):
        return "raw/ is immutable — cannot be written."
    if not norm.startswith(_WIKI_PREFIX):
        return "writes are only allowed under wiki/."
    if norm in _GENERATED:
        return "this file is generated by the system and cannot be written by the agent."
    if not norm.endswith(".md"):
        return "only Markdown (.md) files can be written."
    return None


class ChangeRequestBackend(FilesystemBackend):
    def __init__(self, brain_root: Path, *, read_only: bool = False) -> None:
        # virtual_mode=True confines paths to root (blocks '..' and absolute paths).
        super().__init__(root_dir=brain_root, virtual_mode=True)
        self.brain_root = Path(brain_root).resolve()
        self.staging: dict[str, str] = {}
        self.read_only = read_only
        # Paths the agent tried to write while blocked (read-only audit trail).
        self.write_attempts: list[str] = []
        # Execution telemetry for the run, set by the factory after invoke.
        self.execution_meta: ExecutionMeta | None = None
        # Optional cooperative-cancellation probe; when it returns True the agent
        # aborts at the next model-call boundary. Set by services.
        self.cancel_check: Callable[[], bool] | None = None

    # --- normalization --------------------------------------------------
    @staticmethod
    def _norm(file_path: str) -> str:
        """Relative path to the brain, with POSIX slashes and no leading slash."""
        return file_path.lstrip("/")

    def _escapes_root(self, norm: str) -> bool:
        """True if ``norm`` resolves outside the brain root (path traversal)."""
        resolved = (self.brain_root / norm).resolve()
        return self.brain_root != resolved and self.brain_root not in resolved.parents

    def _guard_write(self, norm: str) -> str | None:
        """Return an error message if writing ``norm`` is disallowed, else None.

        Allow-list policy: only ``wiki/**/*.md`` (minus generated files) is writable.
        """
        if self._escapes_root(norm):
            return "path outside the brain is not allowed."
        return validate_change_path(norm)

    def _disk_content(self, norm: str) -> str | None:
        target = self.brain_root / norm
        if target.is_file():
            return target.read_text(encoding="utf-8")
        return None

    def _current(self, norm: str) -> str | None:
        """Current content visible to the agent: staging has priority over disk."""
        if norm in self.staging:
            return self.staging[norm]
        return self._disk_content(norm)

    def _record_blocked(self, norm: str) -> None:
        self.write_attempts.append(norm)
        logger.warning("read-only backend: blocked write attempt to '%s'.", norm)

    # --- write: capture in staging --------------------------------------
    def write(self, file_path: str, content: str) -> WriteResult:
        norm = self._norm(file_path)
        err = self._guard_write(norm)
        if err is not None:
            return WriteResult(error=f"'{file_path}': {err}")
        if self.read_only:
            self._record_blocked(norm)
            return WriteResult(
                error=f"'{file_path}': read-only operation — writes are not permitted."
            )
        self.staging[norm] = content
        return WriteResult(path=file_path)

    def edit(
        self,
        file_path: str,
        old_string: str,
        new_string: str,
        replace_all: bool = False,
    ) -> EditResult:
        norm = self._norm(file_path)
        err = self._guard_write(norm)
        if err is not None:
            return EditResult(error=f"'{file_path}': {err}")
        if self.read_only:
            self._record_blocked(norm)
            return EditResult(
                error=f"'{file_path}': read-only operation — writes are not permitted."
            )
        current = self._current(norm)
        if current is None:
            return EditResult(error=f"File '{file_path}' not found.")
        occurrences = current.count(old_string)
        if occurrences == 0:
            return EditResult(error=f"old_string not found in '{file_path}'.")
        if occurrences > 1 and not replace_all:
            return EditResult(
                error=(
                    f"old_string appears {occurrences} times in '{file_path}'. "
                    "Use replace_all=True or a more specific snippet."
                )
            )
        count = -1 if replace_all else 1
        self.staging[norm] = current.replace(old_string, new_string, count)
        return EditResult(path=file_path, occurrences=occurrences)

    def read(self, file_path: str, offset: int = 0, limit: int = 2000) -> ReadResult:
        norm = self._norm(file_path)
        if norm in self.staging:
            lines = self.staging[norm].splitlines(keepends=True)
            window = "".join(lines[offset : offset + limit])
            return ReadResult(file_data=FileData(content=window, encoding="utf-8"))
        return super().read(file_path, offset, limit)

    # --- staging overlay for listing/search -----------------------------
    def _staged_children(self, base: str) -> list[str]:
        """Staged file keys that are direct children of directory ``base`` ('' = root)."""
        out: list[str] = []
        for norm in self.staging:
            parent = str(PurePosixPath(norm).parent)
            parent = "" if parent == "." else parent
            if parent == base:
                out.append(norm)
        return out

    def _staged_under(self, base: str) -> list[str]:
        """Staged file keys under directory ``base`` (recursive; '' = whole brain)."""
        if not base:
            return list(self.staging)
        prefix = base + "/"
        return [n for n in self.staging if n == base or n.startswith(prefix)]

    def ls(self, path: str) -> LsResult:
        res = super().ls(path)
        base = self._norm(path).rstrip("/")
        entries = list(res.entries or [])
        seen = {e.get("path") for e in entries}
        for norm in self._staged_children(base):
            virt = "/" + norm
            if virt not in seen:
                entries.append(
                    FileInfo(
                        path=virt,
                        is_dir=False,
                        size=len(self.staging[norm].encode("utf-8")),
                    )
                )
        entries.sort(key=lambda e: e.get("path", ""))
        return LsResult(error=res.error, entries=entries)

    def glob(self, pattern: str, path: str = "/") -> GlobResult:
        res = super().glob(pattern, path)
        base = self._norm(path).rstrip("/")
        pat = pattern.lstrip("/")
        matches = list(res.matches or [])
        seen = {m.get("path") for m in matches}
        for norm in self._staged_under(base):
            rel = norm[len(base) + 1 :] if base else norm
            if fnmatch(rel, pat) or fnmatch(PurePosixPath(norm).name, pat):
                virt = "/" + norm
                if virt not in seen:
                    matches.append(
                        FileInfo(
                            path=virt,
                            is_dir=False,
                            size=len(self.staging[norm].encode("utf-8")),
                        )
                    )
        matches.sort(key=lambda m: m.get("path", ""))
        return GlobResult(error=res.error, matches=matches)

    def grep(
        self,
        pattern: str,
        path: str | None = None,
        glob: str | None = None,
    ) -> GrepResult:
        res = super().grep(pattern, path, glob)
        base = self._norm(path).rstrip("/") if path else ""
        staged = set(self.staging)
        # Drop disk matches for staged files (stale) — staging is the source of truth.
        matches = [m for m in (res.matches or []) if self._norm(m.get("path", "")) not in staged]
        for norm in self._staged_under(base):
            if glob is not None and not fnmatch(PurePosixPath(norm).name, glob):
                continue
            for i, line in enumerate(self.staging[norm].splitlines(), start=1):
                if pattern in line:
                    matches.append(GrepMatch(path="/" + norm, line=i, text=line))
        matches.sort(key=lambda m: (m.get("path", ""), m.get("line", 0)))
        return GrepResult(error=res.error, matches=matches)

    # --- async variants: delegate to synchronous ones -------------------
    async def awrite(self, file_path: str, content: str) -> WriteResult:
        return self.write(file_path, content)

    async def aedit(
        self,
        file_path: str,
        old_string: str,
        new_string: str,
        replace_all: bool = False,
    ) -> EditResult:
        return self.edit(file_path, old_string, new_string, replace_all)

    async def aread(self, file_path: str, offset: int = 0, limit: int = 2000) -> ReadResult:
        return self.read(file_path, offset, limit)

    async def als(self, path: str) -> LsResult:
        return self.ls(path)

    async def aglob(self, pattern: str, path: str = "/") -> GlobResult:
        return self.glob(pattern, path)

    async def agrep(
        self,
        pattern: str,
        path: str | None = None,
        glob: str | None = None,
    ) -> GrepResult:
        return self.grep(pattern, path, glob)

    # --- collect changes ------------------------------------------------
    _CATEGORY = {"create": "new", "update": "edited", "delete": "removed"}

    @staticmethod
    def _confidence_of(content: str) -> str | None:
        """Best-effort extraction of the ``confidence`` frontmatter field."""
        from ..core import frontmatter  # noqa: PLC0415

        try:
            meta, _ = frontmatter.parse(content)
        except Exception:  # noqa: BLE001
            return None
        value = meta.get("confidence") if meta else None
        return str(value) if value is not None else None

    def collect_changes(self) -> list[FileChange]:
        """Compares staging with the disk and returns a list of FileChange (with diffs)."""
        changes: list[FileChange] = []
        for norm in sorted(self.staging):
            new_content = self.staging[norm]
            old = self._disk_content(norm)
            if old is not None and old == new_content:
                continue  # no real change
            operation = "update" if old is not None else "create"
            changes.append(
                FileChange(
                    path=norm,
                    operation=operation,
                    new_content=new_content,
                    diff=make_diff(old or "", new_content, norm),
                    category=self._CATEGORY.get(operation),
                    confidence=self._confidence_of(new_content),
                )
            )
        return changes
